# Numpy

In [1]:
import numpy as np

## vectorisation

In [3]:
import functools as ft
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

def f(x, y=1):
    # return x ** y
    return x ** y

vf = np.vectorize(f)
vf(a, y=2)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### array methods



In [4]:
import numpy as np
import functools as ft
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

def f(x, y):
    return x * y

y = np.array([2, 2, 2, 2])
y = 2
vf = np.vectorize(f)
vf(a, y=y)

#a * y

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

### Working with 3 dimensional arrays

Mulitplying a and b together (f function) will return the same shape array.


In [6]:
a = np.ones([1, 2, 2])
b = np.ones([1, 2, 2]) 
c = np.ones([2, 1, 1])

out = f(a, b)
print(f"Multiping arrays a and b gives the same shape: {out.shape}")
print(out)

out = f(a, c)
print(f"Multiping arrays a and c gives: {out.shape}")
print(out)

Multiping arrays a and b gives the same shape: (1, 2, 2)
[[[1. 1.]
  [1. 1.]]]
Multiping arrays a and c gives: (2, 2, 2)
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [7]:
a.shape


(1, 2, 2)